### PR TITLE
using nokia srlinux ndk bindings and wheels

### PR DESCRIPTION
**Pull request by hellt**
Hi @jbemmel 

wanted to share with you another approach for writing ndk apps in python.

The main distinctive feature of this approach is that
1.  it uses the https://github.com/nokia/srlinux-ndk-py generated bindings, instead of relying on whatever is coming on-box.
2. wheels are leveraged to cleanly build dependencies on a builder container and installing them nicely on a target one

This approach has both pros and cons. The benefit is that you can create your dev environment for NDK as easy as `pip install https://github.com/nokia/srlinux-ndk-py/archive/v21.6.2.zip` and have code completion, hints, etc.

Another benefit is that you create a clean venv on a target system without relying on packages shipped with srlinux and their version. Your venv is all you need and you are in control over what is there.

The downside of that approach could be that you may need to align the NDK version on the box with whatever version you used to develop against. While NDK is not rapidly developing as of now, it may still be the case in the future.

I am curious to hear your thoughts on that approach

PS.
Ignore the changes in `src/bgp-ping-mesh/bgp-ping-mesh.py`, it is just the automated formatting. The only change that is relevant to this PR is the import paths 

PS2. This PR is not meant to be merged as is, but rather to demonstrate another approach to building Py apps

### CODE REVIEW

**Comment by jbemmel** [comment]
Hi @hellt,
Thanks for your contribution.

My initial thoughts are that wheels seem like a useful mechanism, and it is generally a good idea to keep tight control over package versions. However, the exception to this is the NDK bindings - those depend on the specific SRL release running. If there is a difference in version between what's running and what's packaged with the app, then that would be an (unrecoverable) problem.

Note how in the Dockerfile I run Pylint specifically with a protobuf plugin; this allows it to check the calls to the SDK, against the SRL packaged version. You can still run 'pip install' for the dev environment, but I would check it against the latest Docker image tag that is available, to make sure the correct version is used. Either that, or copy it out of the container directly - then you know for sure you have the right version

**Comment by hellt** [comment]
I think relying on the proto bindings available on-box is a wrong development practice. SR Linux happens to have the python bindings available, but nothing for other languages. There is no consistency in that approach from the dev pov.

This discrepancy in the dev workflow IMO is the result of not having a proper ndk versioning scheme. We can't say that srlinux 21.6.4 has ndk v21.6.4; it is a wrong assumption, as NDK hasn't changed since 20.6.x.

Imagine if we would say that srlinux 21.6.4 comes with ndk 1.1.0
then on your dev machine, you will be able to download/generate the lang bindings for ndk 1.1.0, and you will know that you can use the app developed against this API version on a particular set of SR Linux SW versions.

Proto-based APIs, when done right, guarantee backward compatibility, so ndk 1.1.0 will work with SR Linux 20.6.x, unless the app leverages the new features.

I will propose these changes to the ndk versioning scheme soon.

**Comment by jbemmel** [comment]
To me the Python developer experience offered by SRL is actually far superior to most other NOS platforms. Instead of downloading just the NDK, you get to download a full container image with the implementation behind those APIs, and you can run it and verify its behavior in your dev environment (with all the debugging tools you like). You don't need to know anything about the NDK version - you just get the image(s) for the SRL release(s) you need, and off you go. Moreover, using Docker build and pylint you can check your code against the APIs automatically (using a github hook for example); you could auto-generate a report for all available SRLinux versions, with a checkmark for the ones that will work with your app.

By all means, propose a better release versioning scheme - but it's not required to "fix" anything, imho.
If I could choose, I would vote for more features in the NDK (like support for EVPN route types for example)

**Comment by hellt** [comment]
I'll close it as a stale PR

**Pull request closed without merging**
